#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Apr  1 18:58:42 2021

@author: quantum
"""
''' remove duplicate from sorted array '''


li = [int(input()) for _ in range(int(input('range: ')))]
sortedli=sorted(li)
unique_li = []
for i in sortedli:
    if i not in unique_li:
        unique_li.append(i)
print(unique_li)        
        
        
    
    